---
- name: Create directories
  file:
    path: "{{ lookup('vars', item) }}"
    state: directory
  loop: "{{ lookup('varnames', 'ct_path', wantlist=True) }}"

- name: Copy docker-compose.yml
  copy:
    content: "{{ ct_compose | to_nice_yaml }}"
    dest: "{{ ct_path }}/docker-compose.yml"

- name: Start docker-compose.yml
  docker_compose:
    project_src: "{{ ct_path }}"
    pull: "{{ 'ct_update' in ansible_run_tags }}"
  tags: ct_update
