---
- name: Check required variables
  assert:
    that:
      - ct_compose is not search("CHANGEME")
      - ct_user is not search("CHANGEME")
  tags: always

- name: Install acl package for becoming unprivileged user
  package:
    name: acl
  become: true
  tags: ct

- import_tasks: ct.yml
  become_user: "{{ ct_user }}"
  become: true
  tags: ct
