---
- name: Check required variables
  assert:
    that:
      - ct_compose is not search("CHANGEME")
      - ct_path is not search("CHANGEME")
      - ct_user is not search("CHANGEME")
  tags: always

- name: "Create {{ ct_path }}"
  file:
    path: "{{ ct_path }}"
    state: directory
    mode: "{{ ct_mode }}"
    owner: "{{ ct_user }}"
    group: "{{ ct_user }}"
  become: true
  tags: ct

- name: Copy docker-compose.yml
  copy:
    content: "{{ ct_compose | to_nice_yaml }}"
    dest: "{{ ct_path }}/docker-compose.yml"
    mode: "0755"
    owner: "{{ ct_user }}"
    group: "{{ ct_user }}"
  become: true
  tags: ct

- name: Start docker-compose.yml
  docker_compose:
    project_src: "{{ ct_path }}"
    pull: "{{ 'ct_update' in ansible_run_tags }}"
  become: true
  tags: 
    - ct
    - ct_update
    - ct_start
  when: "'ct_start' in ansible_run_tags or 'ct_update' in ansible_run_tags"
